In [1]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

print(torch.__version__)

## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.tensor()`

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#### Remember to practice a lot with TENSOR
#### Play around with the structure
#### Ask questions

### Class 2:

## Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers adn then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers  -> look at data -> update random numbers`

In [19]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5676, 0.5711, 0.6713, 0.3472],
        [0.3921, 0.3502, 0.0542, 0.2818],
        [0.2757, 0.9296, 0.7537, 0.8050]])

In [20]:
random_tensor.ndim

2

### Note: NN(Neural Networks) start with numbers, so working with "images" as seen below starts by converting our `data/input into numbers -> look at data (image tensor) -> adjust those random numbers to better represent our data -> repeat`

In [21]:
 # Craete a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, colour channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim 

(torch.Size([224, 224, 3]), 3)

We finish here today.
## Challenge:
### Create a random tensor of your own with as much dimensions as you like.

## CREATING TENSORS WITH ZEROS AND ONES IN PyTorch

### Zeros and ones

In [22]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Zeroing out a previous tensor

In [23]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Creating a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype #default data type

torch.float32

In [26]:
random_tensor.dtype

torch.float32

the default data type is ``torch.float32``
If we do not set a data type (which we will see later) it automatically uses this as default

 Note: Zeros are more commonly used than Ones

## CREATING A TENSOR RANGE AND TENSORS LIKE OTHER TENSORS

### Creating a range of tensors and tensors-like

In [27]:
# Using torch.range()
torch.range(1, 11)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_1708\2154304566.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1, 11)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Note message: ``UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end)``
So we will be using arange instead.

In [28]:
#Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
#We can also define the step
one_to_ten = torch.arange(start=1, end=11, step=1) #start, end, default step
one_to_ten 

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten) 
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor like is replicating a tensor somewhere else but without the burden of defining what the shape should be

See example above: we have ``ten_zeros`` in same shape as ``one_to_ten``

## DEALING WITH TENSOR DATA TYPES

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [31]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [32]:
float_32_tensor.dtype

torch.float32

Note we put ``dtype=None`` but still got the ``torch.float32`` this is because it is the default data type in PyTorch even if specified as ``None``

In [33]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16) LOOK UP PRECISION IN COMPUTING!!!
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations # if we want PyTorch to track gradient... which we will cover later on.
float_32_tensor

tensor([3., 6., 9.])

``float32 -> 32-bit tensor -> single precision`` which refers to how much space a number takes up in computer memory.
while ``float16 = half precision``

In [35]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_16_tensor * float_32_tensor # This works because we are multiplying a float and a float

tensor([ 9., 36., 81.])

``Int * Float``

In [37]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [38]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [39]:
long_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
long_tensor

tensor([3, 6, 9])

In [40]:
float_32_tensor * long_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attrbutes)

1. Tensors not right datatype - to get  datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on right device - to get device from a tensor, can use `tensor.device`

In [41]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4723, 0.8023, 0.7396, 0.8003],
        [0.1324, 0.7625, 0.5510, 0.2803],
        [0.8726, 0.1993, 0.4443, 0.7333]])

In [42]:
some_tensor.size(), some_tensor.shape 

(torch.Size([3, 4]), torch.Size([3, 4]))

*Note:* tensor.size() and tensor.shape are the same thing, except one is a function and one is an attribute. An attribute is .shape without the brackets and a function has bracket.

In [43]:
# Find out details about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}") # Our device is on CPU by default

tensor([[0.4723, 0.8023, 0.7396, 0.8003],
        [0.1324, 0.7625, 0.5510, 0.2803],
        [0.8726, 0.1993, 0.4443, 0.7333]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## MANIPULATING TENSORS (TENSOR OPERATIONS)
*Note:* When building Neural Networks: Neural Networks are comprised of a lot of mathematical functions the PyTorch code is going to run behind the scenes for us.

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

To find pattern numbers of a data set a Neural Network will combine the above functions in some way, shape, or form. So, it `takes a tensor full of random numbers -> performs some combination of operations (it doesn't have to be all, but any combination) -> manipulate the random numbers some way -> represent a dataset` THAT IS HOW NEURAL NETWORKS LEARN.

In [44]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [45]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

Because we didn't reassign it our tensor remains in its original form (*see below*).

In [46]:
tensor

tensor([1, 2, 3])

See reassign below:

In [47]:
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [48]:
tensor

tensor([10, 20, 30])

In [49]:
# Subtract 10
tensor - 10

tensor([ 0, 10, 20])

In [50]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [51]:
torch.add(tensor, 1)

tensor([11, 21, 31])

*RESEARCH MATRIX MULTIPLICATION!!!*

## MATRIX MULTIPLICATION (PART 1)

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication need to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The result matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [53]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2)) #we get an error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [54]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.3011, 0.8687],
        [0.1203, 0.5690]])

In [55]:
tensor @ tensor

tensor(1400)

In [56]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [57]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [58]:
tensor

tensor([10, 20, 30])

In [59]:
# Matrix multiplication by hand
10*10 + 20*20 + 30*30

1400

In [60]:
# Using for loops
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(1400)


In [61]:
torch.matmul(tensor, tensor) # Faster

tensor(1400)

## MATRIX MULTIPLICATION (PART 2): THE TWO MAIN RULES OF MATRIX MULTIPLICATION

### SEE ABOVE!

## MATRIX MULTIPLICATION (PART 3): DEALING WITH TENSOR SHAPE ERRORS

* One of the most common errors in deep learning: shape errors

In [62]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B) # torch.mm same as torch.matmul (it's an alias for writing less code)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [63]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensor using a **transpose**.

A **transpose** switches the axis or dimensions of a given tensor

In [64]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [65]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [66]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensors_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensors_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## FINDING THE MIN, MAX, MEAN, AND SUM OF TENSORS (TENSOR AGGREGATION)

In [67]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [68]:
# Find the min
torch.min(x), x.min() #You can use any one of these 

(tensor(1), tensor(1))

In [69]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [70]:
# Find the min - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x, dtype=torch.float32), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [71]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## FINDING THE POSITIONAL MIN AND MAX OF TENSORS

In [72]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [73]:
# Find the position in tensor that has the minimun with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [74]:
x[0]

tensor(1)

In [75]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [76]:
x[9]

tensor(91)

## RESHAPING, VIEWING, AND STACKING TENSORS

### Reshaping, stacking, squeezing, and unsqueezing

* Reshaping - reshapes and inputs tensor to a defined state.
* Veiw - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - combining multiple tensors on top of each other (vstack) or side by side (hstack).
* Squeeze - removes all `1` dimensions from tensor.
* Unsqueeze - add a `1` dimension to a target tensor.
*Permute - return a view of the input with dimensions permuted (swapped) in a certain way.

In [2]:
# Let's create a tensor 
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [3]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape 

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [4]:
# Change the view 
z = x.view(1, 9) # View shares a memory with the original tensor.
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [5]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [6]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # Play around with the dim
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [7]:
# torch.squeeze() - remove all single dimensions from a target tensor
print(f"Previuos tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previuos tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [8]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [9]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # (height, width, color_channels)

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # Shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [10]:
x_reshaped.squeeze().shape

torch.Size([9])

In [20]:
x_original[0, 0, 0] = 567890
x_original[0, 0, 0] , x_permuted[0, 0, 0]

(tensor(567890.), tensor(567890.))

## SELECTING DATA FROM TENSORS (INDEXING)

Indexing with PyTorch is similar to indexing with NumPy

In [25]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [26]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [31]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [33]:
# let's index on the most inner bracket (Last dimension)
x[0][0][0] # 0th tensor, 0th index, 0th element

tensor(1)

In [35]:
x[0][1][1]

tensor(9)

In [36]:
x[0][2][2]

tensor(9)

In [37]:
# You can also use ":" to select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [74]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [75]:
# Get all values of the 0 dimension but only the 1 index of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [79]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [86]:
# Index on x to return 9
x, x.shape

# Index on x to return 3, 6, 9

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [84]:
x[:, 2, 2]

tensor([9])

In [99]:
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.
  
And because of this, Python has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [2]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise.
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [3]:
array.dtype

dtype('float64')

In [4]:
tensor.dtype

torch.float64

In [5]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [6]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [7]:
# change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with numbers -> tensor operations -> update random numbers to try and make them better representaions of the data -> again -> again -> again...`

To reduce the randomness in neural network and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [27]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9556, 0.7586, 0.7788, 0.9752],
        [0.0837, 0.0290, 0.5697, 0.3136],
        [0.8124, 0.3320, 0.5073, 0.1225]])
tensor([[0.5757, 0.6427, 0.5928, 0.0619],
        [0.9163, 0.0378, 0.6293, 0.2323],
        [0.5955, 0.8906, 0.1787, 0.6461]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [30]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed 
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to ugrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU there's lots of options
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a bit of setting up, to do this, refer to PyTorch setup documentation

### 2. Check for GPU access with PyTorch

In [34]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

In [35]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

For Pytorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code

E.g. run on GPU if available, else default to CPU