In [2]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

print(torch.__version__)

2.7.1+cpu


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using 'torch.tensor()'

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#### Remember to practice a lot with TENSOR
#### Play around with the structure
#### Ask questions

### Class 2:

## Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers adn then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers  -> look at data -> update random numbers`

In [18]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4576, 0.1920, 0.3155, 0.1061],
        [0.6136, 0.7923, 0.2509, 0.4385],
        [0.0888, 0.5900, 0.7582, 0.5890]])

In [19]:
random_tensor.ndim

2

### Note: NN(Neural Networks) start with numbers, so working with "images" as seen below starts by converting our `data/input into numbers -> look at data (image tensor) -> adjust those random numbers to better represent our data -> repeat`

In [21]:
 # Craete a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, colour channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim 

(torch.Size([224, 224, 3]), 3)

We finish here today.
## Challenge:
### Create a random tensor of your own with as much dimensions as you like.