In [25]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

print(torch.__version__)

2.7.1+cpu


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using 'torch.tensor()'

In [26]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [27]:
scalar.ndim

0

In [28]:
# Get tensor back as Python int
scalar.item()

7

In [29]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [30]:
vector.ndim

1

In [31]:
vector.shape

torch.Size([2])

In [32]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [33]:
MATRIX.ndim

2

In [34]:
MATRIX[0]

tensor([7, 8])

In [35]:
MATRIX[1]

tensor([ 9, 10])

In [36]:
MATRIX.shape

torch.Size([2, 2])

In [37]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [38]:
TENSOR.ndim

3

In [39]:
TENSOR.shape

torch.Size([1, 3, 3])

In [40]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#### Remember to practice a lot with TENSOR
#### Play around with the structure
#### Ask questions

### Class 2:

## Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers adn then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers  -> look at data -> update random numbers`

In [41]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6868, 0.2812, 0.2447, 0.6900],
        [0.3068, 0.3227, 0.9406, 0.3586],
        [0.1794, 0.8556, 0.8391, 0.3634]])

In [42]:
random_tensor.ndim

2

### Note: NN(Neural Networks) start with numbers, so working with "images" as seen below starts by converting our `data/input into numbers -> look at data (image tensor) -> adjust those random numbers to better represent our data -> repeat`

In [43]:
 # Craete a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, colour channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim 

(torch.Size([224, 224, 3]), 3)

We finish here today.
## Challenge:
### Create a random tensor of your own with as much dimensions as you like.

## CREATING TENSORS WITH ZEROS AND ONES IN PyTorch

### Zeros and ones

In [45]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Zeroing out a previous tensor

In [46]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [47]:
# Creating a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [48]:
ones.dtype #default data type

torch.float32

In [49]:
random_tensor.dtype

torch.float32

the default data type is ``torch.float32``
If we do not set a data type (which we will see later) it automatically uses this as default

 Note: Zeros are more commonly used than Ones

## CREATING A TENSOR RANGE AND TENSORS LIKE OTHER TENSORS

### Creating a range of tensors and tensors-like

In [55]:
# Using torch.range()
torch.range(1, 11)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_9512\2154304566.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1, 11)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Note message: ``UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end)``
So we will be using arange instead.

In [56]:
#Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
#We can also define the step
one_to_ten = torch.arange(start=1, end=11, step=1) #start, end, default step
one_to_ten 

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten) 
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor like is replicating a tensor somewhere else but without the burden of defining what the shape should be

See example above: we have ``ten_zeros`` in same shape as ``one_to_ten``

## DEALING WITH TENSOR DATA TYPES

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [63]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [64]:
float_32_tensor.dtype

torch.float32

Note we put ``dtype=None`` but still got the ``torch.float32`` this is because it is the default data type in PyTorch even if specified as ``None``

In [66]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [67]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16) LOOK UP PRECISION IN COMPUTING!!!
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations # if we want PyTorch to track gradient... which we will cover later on.
float_32_tensor

tensor([3., 6., 9.])

``float32 -> 32-bit tensor -> single precision`` which refers to how much space a number takes up in computer memory.
while ``float16 = half precision``

In [81]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [80]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])