In [52]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

print(torch.__version__)

2.7.1+cpu


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.tensor()`

In [53]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [54]:
scalar.ndim

0

In [55]:
# Get tensor back as Python int
scalar.item()

7

In [56]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [57]:
vector.ndim

1

In [58]:
vector.shape

torch.Size([2])

In [59]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [60]:
MATRIX.ndim

2

In [61]:
MATRIX[0]

tensor([7, 8])

In [62]:
MATRIX[1]

tensor([ 9, 10])

In [63]:
MATRIX.shape

torch.Size([2, 2])

In [64]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [65]:
TENSOR.ndim

3

In [66]:
TENSOR.shape

torch.Size([1, 3, 3])

In [67]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#### Remember to practice a lot with TENSOR
#### Play around with the structure
#### Ask questions

### Class 2:

## Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers adn then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers  -> look at data -> update random numbers`

In [68]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1716, 0.8401, 0.3224, 0.1225],
        [0.9950, 0.0299, 0.4316, 0.5243],
        [0.3070, 0.3273, 0.7297, 0.4450]])

In [69]:
random_tensor.ndim

2

### Note: NN(Neural Networks) start with numbers, so working with "images" as seen below starts by converting our `data/input into numbers -> look at data (image tensor) -> adjust those random numbers to better represent our data -> repeat`

In [70]:
 # Craete a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, colour channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim 

(torch.Size([224, 224, 3]), 3)

We finish here today.
## Challenge:
### Create a random tensor of your own with as much dimensions as you like.

## CREATING TENSORS WITH ZEROS AND ONES IN PyTorch

### Zeros and ones

In [71]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Zeroing out a previous tensor

In [72]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [73]:
# Creating a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [74]:
ones.dtype #default data type

torch.float32

In [75]:
random_tensor.dtype

torch.float32

the default data type is ``torch.float32``
If we do not set a data type (which we will see later) it automatically uses this as default

 Note: Zeros are more commonly used than Ones

## CREATING A TENSOR RANGE AND TENSORS LIKE OTHER TENSORS

### Creating a range of tensors and tensors-like

In [76]:
# Using torch.range()
torch.range(1, 11)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_3592\2154304566.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1, 11)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Note message: ``UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end)``
So we will be using arange instead.

In [77]:
#Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
#We can also define the step
one_to_ten = torch.arange(start=1, end=11, step=1) #start, end, default step
one_to_ten 

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten) 
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor like is replicating a tensor somewhere else but without the burden of defining what the shape should be

See example above: we have ``ten_zeros`` in same shape as ``one_to_ten``

## DEALING WITH TENSOR DATA TYPES

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [80]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [81]:
float_32_tensor.dtype

torch.float32

Note we put ``dtype=None`` but still got the ``torch.float32`` this is because it is the default data type in PyTorch even if specified as ``None``

In [82]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [83]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16) LOOK UP PRECISION IN COMPUTING!!!
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations # if we want PyTorch to track gradient... which we will cover later on.
float_32_tensor

tensor([3., 6., 9.])

``float32 -> 32-bit tensor -> single precision`` which refers to how much space a number takes up in computer memory.
while ``float16 = half precision``

In [84]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [85]:
float_16_tensor * float_32_tensor # This works because we are multiplying a float and a float

tensor([ 9., 36., 81.])

``Int * Float``

In [86]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [87]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [88]:
long_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
long_tensor

tensor([3, 6, 9])

In [89]:
float_32_tensor * long_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attrbutes)

1. Tensors not right datatype - to get  datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on right device - to get device from a tensor, can use `tensor.device`

In [90]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7978, 0.5721, 0.0040, 0.0061],
        [0.7545, 0.4737, 0.7254, 0.2697],
        [0.3645, 0.4091, 0.6883, 0.9610]])

In [91]:
some_tensor.size(), some_tensor.shape 

(torch.Size([3, 4]), torch.Size([3, 4]))

*Note:* tensor.size() and tensor.shape are the same thing, except one is a function and one is an attribute. An attribute is .shape without the brackets and a function has bracket.

In [92]:
# Find out details about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}") # Our device is on CPU by default

tensor([[0.7978, 0.5721, 0.0040, 0.0061],
        [0.7545, 0.4737, 0.7254, 0.2697],
        [0.3645, 0.4091, 0.6883, 0.9610]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## MANIPULATING TENSORS (TENSOR OPERATIONS)
*Note:* When building Neural Networks: Neural Networks are comprised of a lot of mathematical functions the PyTorch code is going to run behind the scenes for us.

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

To find pattern numbers of a data set a Neural Network will combine the above functions in some way, shape, or form. So, it `takes a tensor full of random numbers -> performs some combination of operations (it doesn't have to be all, but any combination) -> manipulate the random numbers some way -> represent a dataset` THAT IS HOW NEURAL NETWORKS LEARN.

In [93]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [94]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

Because we didn't reassign it our tensor remains in its original form (*see below*).

In [95]:
tensor

tensor([1, 2, 3])

See reassign below:

In [96]:
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [97]:
tensor

tensor([10, 20, 30])

In [98]:
# Subtract 10
tensor - 10

tensor([ 0, 10, 20])

In [99]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [100]:
torch.add(tensor, 1)

tensor([11, 21, 31])

*RESEARCH MATRIX MULTIPLICATION!!!*

## MATRIX MULTIPLICATION (PART 1)

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication need to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The result matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [105]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2)) #we get an error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [107]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.0897, 0.1463],
        [0.5271, 0.7155]])

In [108]:
tensor @ tensor

tensor(1400)

In [109]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [110]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [111]:
tensor

tensor([10, 20, 30])

In [112]:
# Matrix multiplication by hand
10*10 + 20*20 + 30*30

1400

In [113]:
# Using for loops
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(1400)


In [114]:
torch.matmul(tensor, tensor) # Faster

tensor(1400)

## MATRIX MULTIPLICATION (PART 2): THE TWO MAIN RULES OF MATRIX MULTIPLICATION

### SEE ABOVE!

## MATRIX MULTIPLICATION (PART 3): DEALING WITH TENSOR SHAPE ERRORS

* One of the most common errors in deep learning: shape errors

In [116]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B) # torch.mm same as torch.matmul (it's an alias for writing less code)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [118]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensor using a **transpose**.

A **transpose** switches the axis or dimensions of a given tensor

In [119]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [120]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [123]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensors_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensors_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## FINDING THE MIN, MAX, MEAN, AND SUM OF TENSORS (TENSOR AGGREGATION)

In [144]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [145]:
# Find the min
torch.min(x), x.min() #You can use any one of these 

(tensor(1), tensor(1))

In [146]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [147]:
# Find the min - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x, dtype=torch.float32), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [148]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## FINDING THE POSITIONAL MIN AND MAX OF TENSORS

In [149]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [150]:
# Find the position in tensor that has the minimun with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [151]:
x[0]

tensor(1)

In [152]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [153]:
x[9]

tensor(91)

## RESHAPING, VIEWING, AND STACKING TENSORS 